# juice-shop-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice-shop-victim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juice-shop-victim
  template:
    metadata:
      labels:
        app: juice-shop-victim
    spec:
      containers:
      - name: juice-shop
        image: bkimminich/juice-shop
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: juice-shop-service
spec:
  type: NodePort
  selector:
    app: juice-shop-victim
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000

