apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-ids-victim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-ids-victim
  template:
    metadata:
      labels:
        app: ubuntu-ids-victim
    spec:
      containers:
      - name: ubuntu-ids-victim
        image: shivani1204/ubuntu-ids-victim
        securityContext:
          privileged: true
        imagePullPolicy: Always
        ports:
        - containerPort: 5901
        - containerPort: 6080
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-ids-victim
spec:
  type: NodePort
  selector:
    app: ubuntu-ids-victim
  ports:
  - name: vnc
    port: 5901
    targetPort: 5901
    nodePort: 30006
  - name: novnc
    port: 6080
    targetPort: 6080
    nodePort: 30007

