apiVersion: apps/v1
kind: Deployment
metadata:
  name: kali-victim
  labels:
    app: kali-victim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kali-victim
  template:
    metadata:
      labels:
        app: kali-victim
    spec:
      containers:
      - name: kali-victim
        image: shivani1204/kali-nmap-victim:latest
        ports:
        - containerPort: 6080
        - containerPort: 5900
---
apiVersion: v1
kind: Service
metadata:
  name: kali-victim-service
spec:
  selector:
    app: kali-victim
  ports:
  - name: http
    protocol: TCP
    port: 6080
    targetPort: 6080
    nodePort: 31003
  - name: vnc
    protocol: TCP
    port: 5900
    targetPort: 5900
    nodePort: 32681
  type: NodePort

