apiVersion: apps/v1
kind: Deployment
metadata:
  name: kali-hping-victim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kali-hping-victim
  template:
    metadata:
      labels:
        app: kali-hping-victim
    spec:
      containers:
      - name: kali-hping-victim
        image: shivani1204/kali-hping-victim:latest
        ports:
        - containerPort: 5900  # VNC
        - containerPort: 6080  # noVNC
        securityContext:
          privileged: true  # Allows networking tools like hping3 to work
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
        command: ["/bin/sh", "-c"]
        args:
          - Xvfb :1 -screen 0 1024x768x16 & 
            export DISPLAY=:1 &&
            startxfce4 & 
            x11vnc -display :1 -usepw -forever -listen 0.0.0.0 -rfbport 5900 -shared & 
            /opt/noVNC/utils/novnc_proxy --vnc localhost:5900 --listen 6080

