apiVersion: v1
kind: Service
metadata:
  name: kali-hping-victim-service
spec:
  type: NodePort
  selector:
    app: kali-hping-victim
  ports:
    - name: vnc-port
      protocol: TCP
      port: 5900
      targetPort: 5900
      nodePort: 30000
    - name: novnc-port
      protocol: TCP
      port: 6080
      targetPort: 6080
      nodePort: 30001

