apiVersion: apps/v1
kind: Deployment
metadata:
  name: kali-ids-attacker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kali-ids-attacker
  template:
    metadata:
      labels:
        app: kali-ids-attacker
    spec:
      containers:
      - name: kali-ids-attacker
        image: shivani1204/kali-ids-attacker
        securityContext:
          privileged: true
        imagePullPolicy: Always
        ports:
        - containerPort: 5901
        - containerPort: 6080
---
apiVersion: v1
kind: Service
metadata:
  name: kali-ids-attacker-service
spec:
  type: NodePort
  selector:
    app: kali-ids-attacker
  ports:
  - name: vnc
    port: 5901
    targetPort: 5901
    nodePort: 30008
  - name: novnc
    port: 6080
    targetPort: 6080
    nodePort: 30009

