apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-john-victim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-john-victim
  template:
    metadata:
      labels:
        app: ubuntu-john-victim
    spec:
      containers:
      - name: victim
        image: shivani1204/ubuntu-john-victim:latest
        ports:
        - containerPort: 6080
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-john-victim-service
spec:
  type: NodePort
  selector:
    app: ubuntu-john-victim
  ports:
  - protocol: TCP
    port: 6080
    targetPort: 6080
    nodePort: 30004 # Custom external port

