apiVersion: v1
kind: Service
metadata:
  name: ubuntu-nmap-attacker-service
spec:
  type: NodePort
  selector:
    app: ubuntu-nmap-attacker
  ports:
    - name: novnc-port
      protocol: TCP
      port: 6080
      targetPort: 6080
      nodePort: 30082
    - name: vnc-port
      protocol: TCP
      port: 5900
      targetPort: 5900
      nodePort: 30090

