apiVersion: v1
kind: Service
metadata:
  name: ubuntu-hping-victim-service
spec:
  selector:
    app: ubuntu-hping-victim
  ports:
    - name: vnc-port
      protocol: TCP
      port: 5900
      targetPort: 5900
    - name: novnc-port
      protocol: TCP
      port: 6080
      targetPort: 6080
      nodePort: 31460
  type: NodePort

