apiVersion: apps/v1
kind: Deployment
metadata:
  name: kali-sqlmap-attacker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlmap
  template:
    metadata:
      labels:
        app: sqlmap
    spec:
      containers:
      - name: sqlmap-container
        image: shivani1204/kali-sqlmap-attacker
        ports:
        - containerPort: 6080
        - containerPort: 5900

---

apiVersion: v1
kind: Service
metadata:
  name: kali-sqlmap-service
spec:
  type: NodePort
  selector:
    app: sqlmap
  ports:
  - protocol: TCP
    port: 6080
    targetPort: 6080
    nodePort: 32402

