apiVersion: v1
kind: Service
metadata:
  name: ubuntu-victim-service
spec:
  selector:
    app: ubuntu-victim
  type: NodePort
  ports:
    - protocol: TCP
      port: 6080 # The container's noVNC port
      targetPort: 6080
      nodePort: 30080 # The external port exposed by Minikube for access

