apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-meta-victim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-meta-victim
  template:
    metadata:
      labels:
        app: ubuntu-meta-victim
    spec:
      containers:
      - name: ubuntu-meta-victim
        image: shivani1204/ubuntu-meta-victim
        ports:
        - containerPort: 6080 # noVNC
        - containerPort: 5900 # VNC
        - containerPort: 21   # FTP
        - containerPort: 22   # SSH
        - containerPort: 80   # Web

---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-meta-victim-service
spec:
  type: NodePort
  selector:
    app: ubuntu-meta-victim
  ports:
    - name: novnc
      port: 6080
      targetPort: 6080
      nodePort: 32080  # available
    - name: vnc
      port: 5900
      targetPort: 5900
      nodePort: 32090  # available
    - name: ftp
      port: 21
      targetPort: 21
      nodePort: 32121  # available
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 32122  # available
    - name: web
      port: 80
      targetPort: 80
      nodePort: 32180  # available

