apiVersion: apps/v1
kind: Deployment
metadata:
  name: kali-metasploit-attacker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metasploit-attacker
  template:
    metadata:
      labels:
        app: metasploit-attacker
    spec:
      containers:
      - name: metasploit-attacker
        image: shivani1204/kali-metasploit-attacker
        ports:
        - containerPort: 6080

---

apiVersion: v1
kind: Service
metadata:
  name: kali-metasploit-attacker-service
spec:
  selector:
    app: metasploit-attacker
  ports:
    - protocol: TCP
      port: 6080   # Internal service port
      targetPort: 6080  # Container port
      nodePort: 32403  # Minikube will expose this
  type: NodePort

