apiVersion: apps/v1
kind: Deployment
metadata:
  name: kali-john-attacker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kali-john-attacker
  template:
    metadata:
      labels:
        app: kali-john-attacker
    spec:
      containers:
      - name: kali-john-attacker
        image: shivani1204/kali-john-attacker
        ports:
        - containerPort: 6080
---
apiVersion: v1
kind: Service
metadata:
  name: kali-john-attacker-service
spec:
  type: NodePort
  selector:
    app: kali-john-attacker
  ports:
  - protocol: TCP
    port: 6080
    targetPort: 6080
    nodePort: 30005

