apiVersion: apps/v1
kind: Deployment
metadata:
  name: kali-wireshark-attacker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kali-wireshark-attacker
  template:
    metadata:
      labels:
        app: kali-wireshark-attacker
    spec:
      containers:
      - name: kali-wireshark-attacker
        image: shivani1204/kali-wireshark:latest
        ports:
        - containerPort: 5900
        - containerPort: 6080

---
apiVersion: v1
kind: Service
metadata:
  name: kali-wireshark-attacker-service
spec:
  selector:
    app: kali-wireshark-attacker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6080
      nodePort: 31249
  type: NodePort


