apiVersion: v1
kind: Service
metadata:
  name: ubuntu-wireshark-attacker-service
spec:
  selector:
    app: ubuntu-wireshark-attacker
  ports:
  - protocol: TCP
    port: 6080
    targetPort: 6080
    nodePort: 30506
  type: NodePort

