apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-04-28T12:26:25Z"
  generation: 1
  labels:
    app: nessus
  name: nessus
  namespace: default
  resourceVersion: "67434"
  uid: a5be196d-19a5-4ff8-b747-27bd3763eb97
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nessus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nessus
    spec:
      containers:
      - image: tenableofficial/nessus:latest
        imagePullPolicy: Always
        name: nessus
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-04-28T12:26:25Z"
    lastUpdateTime: "2025-04-28T12:26:28Z"
    message: ReplicaSet "nessus-5dc55f7d8d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-04-28T14:34:07Z"
    lastUpdateTime: "2025-04-28T14:34:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
